name: pragdave_me
title: pragdave—the coding gnome
email: dave@pragdave.me
description: >
  The Coding Gnome helps developers code better. We look at the languages,
  tools, and techniques used by successful programmers. We work on the
  new stuff, so your skills can develop to meet future needs. And we
  have some fun along the way. Dave Thomas. @pragdave

    
baseurl:   ""
permalink: /blog/:year/:month/:day/:title.html
url:       https://pragdave.me

tag_page:  /blog/tags

assets:
  compress:
      css: true
      js:  false
  features:
    automatic_img_size: false
  sources:
    - _assets/bower
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _vendor/

exclude:
  - .bowerrc
  - .travis.yml
  - bin/*
  - bower.json
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor

ga_analytics: 'UA-46932612-1'
disqus:
  shortname: pragdave

gems:
  - jekyll-assets
  - jekyll-sitemap


